version: "3.7"

services:

  flask:
    build: ./flask
    container_name: cloud_project_flask
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: cloud_project_nginx
    restart: always
    ports:
      - "80:80"